### ISSUE TITLE
Cannot install to Symfony 5 

### ISSUE THREAD

**Issue by exaland** [tattali/CalendarBundle#18]
Hello Everyone !

I need to install your bundle, but I end up with this error when installing on Symfony 5

`Problem 1`

`tattali/calendar-bundle v1.1.6 requires symfony/dependency-injection ^3.4 || ^4.0`

Thanks for your help

**Comment by tattali** [comment]
@exaland @xmathieu13 the 1.1.8 version should handle your errors
