### ISSUE TITLE
probleme

### ISSUE THREAD

**Issue by xmathieu13** [tattali/CalendarBundle#19]
Bonjour j'ai installée votre bunddle sous symfony 5.0. Après avoir suivi toute les instructions de base, j'ai toujours une erreur 500 quand j'envoie la requête ajax.
Voici le la dénomination de l'erreur dans le profiler de Symfony:
'The controller for URI "/fc-load-events" is not callable. Controller "CalendarBundle:Calendar:load" does neither exist as service nor as class'. Malgré les recherches et les tentaives je suis à cours de solution. Merci de m'indiquer a marche a suivre pour résoudre le problême.

**Comment by tattali** [comment]
duplicate of #18
