### ISSUE TITLE
Evènement "eventAfterAllRender" ne fonctionne pas

### ISSUE THREAD

**Issue by bastien70** [tattali/CalendarBundle#20]
Salut Théo !

Je sais pas si ça vient de ton bundle, mais lorsque j'essaie de mettre l'évènement eventAfterAllRender, il est ignoré.

https://fullcalendar.io/docs/v3/eventAfterAllRender

Dans le template lorsque je configure FullCalendar, j'essaie de mettre l'event :

`eventAfterAllRender: function(view) {
                console.log("test");
            },`
Mais aucune sortie

Tandis que sur une version sans ton bundle, l'event fonctionne : http://jsfiddle.net/matthias_h/tsbLby4e/

Est-ce que ça vient de ton bundle ?

**Comment by tattali** [comment]
cela  ne vient pas du bundle, j'espère que tu as trouvé
