### ISSUE TITLE
Event filter with checkboxes

### ISSUE THREAD

**Issue by mtetuaoho** [tattali/CalendarBundle#21]
Hello everyone,

So, I download the tattali/calendar-bundle, I created all of my entities and now I would like to create an event filter for each section. Basically, an event is linked to a section and i would like to add some checkboxes that will be the different sections that exists and when I click on one checkbox, the only events that will be shown on the calendar will be the events from the section of this checkbox.
I already check online to see if someone have the same issue than me but I do not understand verry well how  the filters worked because I'm a beginner.

If someone could help me !!!! 
Thank yoouuuu

**Comment by tattali** [comment]
this do not concern this bundle sorry.
