### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error) + (fc-load-events)

### ISSUE THREAD

**Issue by jorgeale90** [tattali/CalendarBundle#22]
Hi:
I am using your bundle, I follow the steps for implementation, but when I create an event for me to appear on the calendar this error is shown.
Thank you

![1](https://user-images.githubusercontent.com/11742275/75190889-e587ca00-5716-11ea-8075-780f9fff98a1.png)
![2](https://user-images.githubusercontent.com/11742275/75190894-e7518d80-5716-11ea-8b92-06dba7edd1bf.png)

**Comment by tattali** [comment]
hi are you using webpack or use directly js ?

**Comment by jorgeale90** [comment]
I use JS direct...

**Comment by tattali** [comment]
Sorry I forgot to answer, do you still have the issue?
Can you show me your view and subscriber pls?

**Comment by Kami99** [comment]
your service is not called
