### ISSUE TITLE
Dépréciation The "Psr\Container\ContainerInterface" autowiring alias is deprecated

### ISSUE THREAD

**Issue by bastien70** [tattali/CalendarBundle#26]
Bonjour, il y a une dépréciation ici : 

![image](https://user-images.githubusercontent.com/53140475/83767929-7d824180-a67e-11ea-9105-556e7eee83c2.png)

Survenue en Symfony 5.1

**Comment by TeLiXj** [comment]
I found the same deprecation but is our fault, not of CalendarBundle. 
You can read here https://github.com/symfony/demo/issues/1117#issuecomment-642563336 that you must update your recipes to add the new changes added SF5.1. After do it I don't have any deprecation :)

**Comment by bastien70** [comment]
> I found the same deprecation but is our fault, not of CalendarBundle.
> You can read here [symfony/demo#1117 (comment)](https://github.com/symfony/demo/issues/1117#issuecomment-642563336) that you must update your recipes to add the new changes added SF5.1. After do it I don't have any deprecation :)

Hey ! I did not know the command `composer recipes:install --force` thanks !
On the other hand, I already used to update my recipes with : 

`composer recipes` and `composer recipes:install vendor/package --force -v`

Therefore, I did not have recipes to update currently. This allows me to tell you that unfortunately, that has not changed the problem. My recipes are all up to date but the depreciation is still present

**Comment by tattali** [comment]
Hi, thanks for your feedback!

When I created a new project with 5.1, I didn't find any depreciation, so you probably have an old piece of code.

The old way to `compose composer: install --force` is to delete the` vendor` and `var` folders and delete the` composer.lock`, then run `composer install` this reinstalls everything just like a fresh start.
Then use the git diff to see the changes

If the error persists you can also create a new project next to it and add the same packages to compare the files (maybe some of them should be deleted).

**Comment by Nelly34** [comment]
Hi,
I created a new project with 5.1 and I install the bundle with the command:
 composer require tattali/calendar-bundle
Nothing else, just symfont 5.1 and calendar-bundle, I have same deprecation in my debug bar.

**Comment by TeLiXj** [comment]
I can confirm that the deprecation continues, only disappear for me just the first time after clear cache :(

**Comment by tattali** [comment]
If it disappear after clean cache, I donit think this is a real issue can you confirm ? @TeLiXj and @bastien70 
Thanks!

**Comment by bastien70** [comment]
> If it disappear after clean cache, I don't think this is a real issue. Can you confirm ? @TeLiXj, @Nelly34 and @bastien70
> Thanks!

I just checked after a clear cache, and for my part, it doesn't change anything, the depreciation is still present

**Comment by tattali** [comment]
Can you reproduce it or share your projet with me?

Thanks!

**Comment by bastien70** [comment]
> Can you reproduce it or share your project with me?
> 
> Thanks!

Yep, I created a new symfony 5.1 project, and required your bundle.

https://github.com/bastien70/test-calendar-bundle

If you launch the server, and go home, you will see the deprecation

**Comment by tattali** [comment]
Thanks to all! The fix will be in the next release
