### ISSUE TITLE
Impossible de mettre à jour le bundle

### ISSUE THREAD

**Issue by bastien70** [tattali/CalendarBundle#27]
Bonjour,

Dans mon composer.json j'ai actuellement dans mes require : 

`"tattali/calendar-bundle": "^1.1",`

J'ai vu qu'il y avait une version 1.2.
J'ai modifié mon require pour

`"tattali/calendar-bundle": "^1.2",`

et tenté un update, mais à chaque fois, j'obtiens **"tattali/calendar-bundle": "^1.1",**

**Comment by bastien70** [comment]
Bonjour, ah oui pardon, je suis sur **Symfony 5.1**

**Composer.json** : https://pastebin.com/HNpNdMU9

**Comment by tattali** [comment]
Il ne semble pas y avoir de conflits avec les paquets du bundle.
Dans votre `composer.lock`, quelle version du bundle est inscrite ?
Si voulez, vous pouvez le partager pour que je regarde.

**Comment by bastien70** [comment]
Oui, voici la partie du **composer.lock** lié au bundle : https://pastebin.com/vYeDAjhJ

Et le **composer.lock** entier si nécessaire : https://pastebin.com/7t8t6gkX

**Comment by tattali** [comment]
Je vais regarder cela.
Le par la mention `"tattali/calendar-bundle": "^1.1"`, le `^` du `composer.json` indique la version minimale soit : toutes les versions mineur de la `v1`à partir de `1.1`. `1.1` à sitrictement inférieur à `2.0`
