### ISSUE TITLE
App\Entity\Booking object not found by the @ParamConverter annotation.

### ISSUE THREAD

**Issue by n-tsvetkov-krez** [tattali/CalendarBundle#29]
Hi,

I followed all steps, but finally I got 

`App\Entity\Booking object not found by the @ParamConverter annotation.`

It is here:

{
    "route": "booking_show",
    "route_parameters": {
        "_route": "booking_show",
        "_controller": "App\\Controller\\BookingController::show",
        "id": "calendar"
    },
    "request_uri": "http://127.0.0.1/dashboard/vacations/public/booking/calendar",
    "method": "GET"
}

What I'm doing wrong?

composer.json
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.2.5",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/apache-pack": "^1.0",
        "symfony/asset": "5.0.*",
        "symfony/console": "5.0.*",
        "symfony/dotenv": "5.0.*",
        "symfony/expression-language": "5.0.*",
        "symfony/flex": "^1.3.1",
        "symfony/form": "5.0.*",
        "symfony/framework-bundle": "5.0.*",
        "symfony/http-client": "5.0.*",
        "symfony/intl": "5.0.*",
        "symfony/mailer": "5.0.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/notifier": "5.0.*",
        "symfony/orm-pack": "*",
        "symfony/process": "5.0.*",
        "symfony/security-bundle": "5.0.*",
        "symfony/serializer-pack": "*",
        "symfony/string": "5.0.*",
        "symfony/translation": "5.0.*",
        "symfony/twig-pack": "*",
        "symfony/validator": "5.0.*",
        "symfony/web-link": "5.0.*",
        "symfony/yaml": "5.0.*",
        "tattali/calendar-bundle": "^1.2"
    },
    "require-dev": {
        "symfony/debug-pack": "*",
        "symfony/maker-bundle": "^1.0",
        "symfony/profiler-pack": "*",
        "symfony/test-pack": "*"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": true,
            "require": "5.0.*"
        }
    }
}

![image](https://user-images.githubusercontent.com/68046527/87042753-c472d200-c1fc-11ea-8ad0-ed4bbe88a321.png)

**Comment by kryst3q** [comment]
Had the same issue. Look at this answer to solve it: https://stackoverflow.com/a/53859651

**Comment by tattali** [comment]
thx for your answer @kryst3q I should have thought about it!

@n-tsvetkov-krez have you find a way to solve your issue?

**Comment by n-tsvetkov-krez** [comment]
Meanwhile I started new project and abandoned this one. May be I'll use it later.

**Comment by n-tsvetkov-krez** [comment]
Meanwhile I started new project and abandoned this one. May be I'll use it later.

@kryst3q Thank you! I'll take a look.
