### ISSUE TITLE
What is /fc_load_events?

### ISSUE THREAD

**Issue by ehymel** [tattali/CalendarBundle#3]
I'd like to use your package, but this appears to rely on a file that lives at `/fc_load_events` in your examples. You never specify what file this refers to. It seems like it would point to the file you list as your Listener, but of course a Listener does not live at a URL from the web. It's also not clear to me when the Listener is supposed to be summoned. Can you help clarify these points?

**Comment by ehymel** [comment]
I found the answer. Your examples reference `/fc_load_events`, but the actual path referenced in your file `@CalendarBundle/Resources/config/routing.yaml` is `fc-load-events`. Once I corrected this in my twig file, all works fine. You just need to update your documentation accordingly. Thanks for the bundle!

**Comment by tattali** [comment]
Thanks ! I just see your issue by luck. Next time do not hesitate to contribute or let the issue open until the bug is fixed ;)

**Comment by mathildegrimal** [comment]
Hello !
I'm using your bundle in a Symfony project, but in the back end part. When I was using it in the front, it was working perfectly, but now I think there is a problem to load the events as the script JS is calling the path 'fc_load_events", do you have an idea to fix this ?
thank you by advance
