### ISSUE TITLE
Date au format français

### ISSUE THREAD

**Issue by Carlos57000** [tattali/CalendarBundle#30]
Bonjour Tattali,

Merci beaucoup pour ce super outil.

Tout fonctionne bien sauf que j'ai essayé de franciser les champs de la route 8000/booking/new mais je ne vois pas où agir en ce qui concerne le formulaire en soi.

Du coup pour chaque nouvel événement, le formulaire affiche "begin at jan 1 2015" et je souhaiterais avoir le format français en affichant par défaut la date du jour ou au moins 2020.

Je souhaiterais aussi que pour les minutes on ne puisse choisir que par créneaux de 15mn mais pareil, je ne vois pas comment faire.

Je précise que je débute à peine dans le développement et je n'ai pas trouvé dans la doc comment faire.

Merci.

**Comment by Carlos57000** [comment]
Pour ceux qui auraient le même problème, j'ai trouvé comment faire.

Afin d’afficher le calendrier en français, j’ai dû recourir à quelques modifications dans le fichier calendar.html.twig en ajoutant :

locale: ‘fr’,

buttonText: 
            {
               today:    'Aujourd\'hui',
                month:    'Mois',
                week:     'Semaine',
                day:      'Jour',
            }



La doc le mentionne mais je trouve que ça ne saute pas aux yeux à première vue.

Ce sont ces liens : https://fullcalendar.io/docs/locale et https://fullcalendar.io/docs/buttonText

------------------------------------------
Du coup le seul problème restant est celui de la route booking/new (begin at jan 1 2015)

**Comment by tattali** [comment]
Bonjour,
vous voulez probablement utiliser un datetimepicker. 
Voici un tutoriel vous décrivant une solution pour le mettre en place : [ici](https://symfonycasts.com/screencast/symfony3-forms/date-picker-field) ou [là](https://symfonycasts.com/screencast/symfony-forms/datetime-type-transforming)
Dans le tuto, le paquet est un datepicker (donc sans possibilité d'ajouter l'heure).
Il existe des centaines de datepicker ou datetimepicker. Je vous laisse choisir le plus adapté.

**Comment by Carlos57000** [comment]
Merci pour votre réponse.

Vous avez vu juste, je comptais utiliser un datetimepicker.

Auriez-vous éventuellement un conseil à me donner concernant l'endroit où se trouve ce qui affiche par défaut dans la route booking/new "begin at jan 1 2015" svp ?

Est-ce que c'est le fichier src>Form>BookingType.php ?
