### ISSUE TITLE
Comment éviter doublons de réservation et heure de fin< heure de début

### ISSUE THREAD

**Issue by Carlos57000** [tattali/CalendarBundle#31]
Bonjour Tattali,

Je vous contacte car je souhaiterais savoir :

1. comment paramétrer le calendrier pour éviter un doublon de réservation : ex : si le créneau 24/08 16h 16h15 est déjà pris, comment bloquer toute nouvelle réservation sur ledit créneau en affichant un message "veuillez modifier votre créneau" ?

2. j'ai constaté qu'on pouvait définir une heure de fin < heure de début d'un événement : est-ce un bug ? Comment empêcher que cela se produise ?

Merci.

**Comment by sofianetouati** [comment]
Bonsoir. Le problème à-t-il été résolu? J'ai le même besoin..Merci.

**Comment by Carlos57000** [comment]
> Bonsoir. Le problème à-t-il été résolu? J'ai le même besoin..Merci.

Bonsoir je ne suis pas sûr d'avoir eu une réponse à l'époque de Tattali ni même d'avoir réussi à régler le pb.

Mon projet étant ancien, j'ai repassé en revue mon code de l'époque mais je ne pense pas être parvenu à trouver une solution en ce temps là.

Navré.
