### ISSUE TITLE
"No route found for "POST /fc-load-events"

### ISSUE THREAD

**Issue by zarbagmedmehdi** [tattali/CalendarBundle#32]
Bonjour ,en suivant le tutoriel associé a ce bundle j'ai réalisé tout les taches demandés ,or   fc-load-event me donne 404  le navigateur ne peut pas savoir cette route Merci de me renseignier sur ce probléme

**Comment by missCorie** [comment]
Hello, I have the same problem
Unable to generate a URL for the named route "fc_load_events" as such route does not exist.

**Comment by zarbagmedmehdi** [comment]
did you add this line in bundles.php 
    Knp\Bundle\PaginatorBundle\KnpPaginatorBundle::class => ['all' => true],
@missCorie

**Comment by missCorie** [comment]
Yes. I think I found it, I commented the lines below. Thanks
 App\EventListener\CalendarListener:
       # tags:
        #   - { name: 'kernel.event_listener', event: 'calendar.set_data', method: onCalendarSetData}

**Comment by tattali** [comment]
Hi!

Sorry for this late answer to the issue.

@zarbagmedmehdi and @missCorie which version of symfony are you using?

@zarbagmedmehdi was adding `CalendarBundle\CalendarBundle::class` was the answer to your issue?

@missCorie do not hesitate to consult the documention, especially the [fourth part](https://github.com/tattali/CalendarBundle/blob/master/src/Resources/doc/doctrine-crud.md#4-use-an-event-subscriber-to-connect-all-of-this-together) 

Thank you!

**Comment by zarbagmedmehdi** [comment]
yes im using symfony 5.1

**Comment by tattali** [comment]
> yes im using symfony 5.1

weird normally it's done automatically by composer

**Comment by tattali** [comment]
did you deleted the `post-install-cmd` or `post-update-cmd` scripts in your `composer.json` ?
```
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
```

**Comment by missCorie** [comment]
Try to add a string parameter to the new Event( )

**Comment by aa-aahmed** [comment]
**Symfony 4.4.20**

Boys, I have the same issue. Bundle is enabled, Services are registered.

An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fc_load_events" as such route does not exist.").

Composer: 
```
"scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },

```
