### ISSUE TITLE
Duplicate every event

### ISSUE THREAD

**Issue by skPink** [tattali/CalendarBundle#34]
Hi. 

I have duplication of my all event but on database i have just 1 entry

![Capture d’écran 2020-11-01 à 19 41 36](https://user-images.githubusercontent.com/10786016/97811355-5dc96680-1c7a-11eb-9c1d-cb29821b08e9.png)

**Comment by missCorie** [comment]
Hi !
I have same problem !

**Comment by tattali** [comment]
Do you still face this issue ? this probably in your event listener

**Comment by skPink** [comment]
@tattali My event listener is correct same of tutorial

`document.addEventListener('DOMContentLoaded', () => {
            var calendarEl = document.getElementById('calendar-holder');

            var calendar = new FullCalendar.Calendar(calendarEl, {
                defaultView: 'dayGridMonth',
                themeSystem: 'bootstrap',
                editable: true,
                locale: 'fr',
                eventSources: [
                    {
                        url: "{{ path('fc_load_events') }}",
                        method: "POST",
                        extraParams: {
                            filters: JSON.stringify({})
                        },
                        failure: () => {
                            // alert("There was an error while fetching FullCalendar!");
                        },
                    },
                ],
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay',
                },
                plugins: [ 'interaction', 'dayGrid', 'timeGrid' ], // https://fullcalendar.io/docs/plugin-index
                timeZone: 'UTC',
            });
            calendar.render();
        });`

**Comment by tattali** [comment]
Oh my bad, not event listener, event subscriber !

**Comment by skPink** [comment]
no problem this : 

`
<?php

namespace App\EventSubscriber;

use App\Repository\CommunityPublicationRepository;
use CalendarBundle\CalendarEvents;
use CalendarBundle\Entity\Event;
use CalendarBundle\Event\CalendarEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class CalendarSubscriber implements EventSubscriberInterface
{
    /**
     * @var CommunityPublicationRepository
     */
    private $communityPublication;

    /**
     * @var UrlGeneratorInterface
     */
    private $router;

    public function __construct(
        CommunityPublicationRepository $communityPublicationRepository,
        UrlGeneratorInterface $router
    ) {
        $this->communityPublication = $communityPublicationRepository;
        $this->router = $router;
    }

    public static function getSubscribedEvents()
    {
        return [
            CalendarEvents::SET_DATA => 'onCalendarSetData',
        ];
    }

    public function onCalendarSetData(CalendarEvent $calendar)
    {
        $start = $calendar->getStart();
        $end = $calendar->getEnd();
        $filters = $calendar->getFilters();

        // Modify the query to fit to your entity and needs
        // Change booking.beginAt by your start date property
        $publications = $this->communityPublication
            ->createQueryBuilder('cm')
            ->where('cm.post_date BETWEEN :start and :end')
            ->setParameter('start', $start->format('Y-m-d H:i:s'))
            ->setParameter('end', $end->format('Y-m-d H:i:s'))
            ->getQuery()
            ->getResult()
        ;


        foreach ($publications as $publication) {
            // this create the events with your data (here booking data) to fill calendar
            $endDate = $publication->getPostDate();
            $endDate->modify('+ 1 hour');

            $title = $publication->getStatusIcon().' '.$publication->getTitle();

            $publicationEvent = new Event(
                $title,
                $publication->getPostDate(),
                $endDate
            );

            /*
             * Add custom options to events
             *
             * For more information see: https://fullcalendar.io/docs/event-object
             * and: https://github.com/fullcalendar/fullcalendar/blob/master/src/core/options.ts
             */

            $publicationEvent->setOptions([
                'backgroundColor' => $publication->getSocialColor(),
                'borderColor' => $publication->getSocialColor(),
            ]);
            $publicationEvent->addOption(
                'url',
                $this->router->generate('community_publication_show', [
                    'id' => $publication->getId(),
                ])
            );

            // finally, add the event to the CalendarEvent to fill the calendar
            $calendar->addEvent($publicationEvent);
        }
    }
}

`

**Comment by skPink** [comment]
@tattali Any news ?

**Comment by tattali** [comment]
Sorry for the delay do you have something in your `services.yaml` ?

**Comment by skPink** [comment]
@tattali No problem 

`# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    picture_directory: '%kernel.project_dir%/public/uploads/pictures'
    pdf_signed_directory: '%kernel.project_dir%/public/uploads/accounting/quote/pdf/signed'
    admin_cm_publication_post: '%kernel.project_dir%/public/uploads/admin/cm/publication'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventSubscriber\CalendarSubscriber:
        tags:
            - { name: 'kernel.event_listener', event: 'calendar.set_data', method: onCalendarSetData }`

**Comment by tattali** [comment]
weird i try to reproduce but I dont have the error 
Can you make un reproducer ?

**Comment by tattali** [comment]
you need to only have 

```yaml
App\EventSubscriber\CalendarSubscriber:
```

not 

```yaml
App\EventSubscriber\CalendarSubscriber:
    tags:
        - { name: 'kernel.event_listener', event: 'calendar.set_data', method: onCalendarSetData }
```

**Comment by tattali** [comment]
even without 
```yaml
App\EventSubscriber\CalendarSubscriber:
```
this sould work because autoconfigure is true

**Comment by skPink** [comment]
@tattali Is work perfect thx
