### ISSUE TITLE
Handle request from select box

### ISSUE THREAD

**Issue by Skatsarov123** [tattali/CalendarBundle#35]
Hi there
First thanks for this bundle.I want to create front-end drop down filter,but i have a problem with form request.

Argument 2 passed to App\EventSubscriber\CalendarSubscriber::onCalendarSetData() must be an instance of Symfony\Component\HttpFoundation\Request, string given, called in /var/www/html/faa/vendor/symfony/event-dispatcher/Debug/WrappedListener.php on line 126

not sure where to handle request to  make response with filtered events

thanks

**Comment by tattali** [comment]
Hi can you share your event subcriber please ?

**Comment by Skatsarov123** [comment]
<?php

namespace App\EventSubscriber;

use App\Repository\BookingRepository;
use CalendarBundle\CalendarEvents;
use CalendarBundle\Entity\Event;
use CalendarBundle\Event\CalendarEvent;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;


class CalendarSubscriber extends AbstractController implements EventSubscriberInterface
{
    private BookingRepository $bookingRepository;
    private UrlGeneratorInterface $router;

    public function __construct(
        BookingRepository $bookingRepository,
        UrlGeneratorInterface $router
    )
    {
        $this->bookingRepository = $bookingRepository;
        $this->router = $router;
    }
    public static function getSubscribedEvents()
    {
        return [
            CalendarEvents::SET_DATA => 'onCalendarSetData',
        ];
    }
    /**
     * @param CalendarEvent $calendar
     * @param Request $request
     * @return Response
     */

    public function onCalendarSetData( CalendarEvent $calendar,Request $request):Response
    {
        // Modify the query to fit to your entity and needs
        // Change booking.beginAt by your start date property

        $status = $request->get('statusChoice');
        if ($status === '0') {
            $bookings = $this->bookingRepository->findBy(['author' => $this->getUser(), 'status' => '0']);

        } else {
            $bookings = $this->bookingRepository->findBy(['author' => $this->getUser()]);
        }
        foreach ($bookings as $booking) {

            // this  create the events with your data (here booking data) to fill calendar
            $bookingEvent = new Event(
                $booking->getTitle(),
                $booking->getloadingDate(),
                $booking->getUnloadingDate(),
                $filters = $calendar->getFilters(),
            );

            /*
             * Add custom options to events
             *
             * For more information see: https://fullcalendar.io/docs/event-object
             * and: https://github.com/fullcalendar/fullcalendar/blob/master/src/core/options.ts
             */
            if ($booking->getStatus() != 0) {
                $bookingEvent->setOptions([
                    'backgroundColor' => 'grey',
                    'borderColor' => 'grey',
                ]);
            } else {
                $bookingEvent->setOptions([
                    'backgroundColor' => 'matblue',
                    'borderColor' => 'matblue',

                ]);
            }
            $bookingEvent->addOption(
                'url',
                $this->router->generate('booking_show', [
                    'id' => $booking->getId(),
                ])
            );

            // finally, add the event to the CalendarEvent to fill the calendar
            $calendar->addEvent($bookingEvent);
        }
    }
}

**Comment by tattali** [comment]
And your entity booking

**Comment by Skatsarov123** [comment]
`<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 */
class Booking
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     * @ORM\Id
     */
    private $id;
    /**
     * @ORM\Column(type="string", length=255 ,nullable=true)
     */
    private $title;
    /**
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeInterface $loadingDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeInterface $unloadingDate;

    /**
     * @ORM\Column(type="string")
     */
    private $truck_id;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $loadingAddress;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $unloadingAddress;
    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $pricePerKm;
    /**
     * @var Driver
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Driver",inversedBy="cargoes")
     */
    private Driver $drivers;
    /**
     * @ORM\Column(type="integer" )
     */
    private int $status = 0;
    /**
     * @var User
     *@ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     */
    private User $author;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLoadingDate(): ?\DateTimeInterface
    {
        return $this->loadingDate;
    }

    public function setLoadingDate(\DateTimeInterface $loadingDate): self
    {
        $this->loadingDate = $loadingDate;

        return $this;
    }

    public function getUnloadingDate(): ?\DateTimeInterface
    {
        return $this->unloadingDate;
    }

    public function setUnloadingDate(?\DateTimeInterface $unloadingDate = null): self
    {
        $this->unloadingDate = $unloadingDate;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPricePerKm()
    {
        return $this->pricePerKm;
    }

    /**
     * @param mixed $pricePerKm
     */
    public function setPricePerKm($pricePerKm): void
    {
        $this->pricePerKm = $pricePerKm;
    }

    /**
     * @return mixed
     */
    public function getUnloadingAddress()
    {
        return $this->unloadingAddress;
    }

    /**
     * @param mixed $unloadingAddress
     */
    public function setUnloadingAddress($unloadingAddress): void
    {
        $this->unloadingAddress = $unloadingAddress;
    }

    /**
     * @return mixed
     */
    public function getTruckId()
    {
        return $this->truck_id;
    }

    /**
     * @param mixed $truck_id
     */
    public function setTruckId($truck_id): void
    {
        $this->truck_id = $truck_id;
    }

    /**
     * @return mixed
     */
    public function getLoadingAddress()
    {
        return $this->loadingAddress;
    }

    /**
     * @param mixed $loadingAddress
     */
    public function setLoadingAddress($loadingAddress): void
    {
        $this->loadingAddress = $loadingAddress;
    }



    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->loadingAddress." to ".$this->unloadingAddress;
    }

    /**
     * @param mixed $title
     */
    public function setTitle($title): void
    {
        $this->title = $title;
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }
    /**
     * @param mixed $status
     */
    public function setStatus($status): void
    {
        $this->status = $status;
    }
    /**
     * @return User
     */
    public function getAuthor(): User
    {
        return $this->author;
    }

    /**
     * @param User $author
     *
     */
    public function setAuthor(User $author )
    {
        $this->author = $author;
    }
    /**
     * @return Driver
     */
    public function getDrivers(): Driver
    {
        return $this->drivers;
    }

    /**
     * @param Driver $drivers
     */
    public function setDrivers(Driver $drivers): void
    {
        $this->drivers = $drivers;
    }


}`

**Comment by Skatsarov123** [comment]
`<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 */
class Booking
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     * @ORM\Id
     */
    private $id;
    /**
     * @ORM\Column(type="string", length=255 ,nullable=true)
     */
    private $title;
    /**
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeInterface $loadingDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?\DateTimeInterface $unloadingDate;

    /**
     * @ORM\Column(type="string")
     */
    private $truck_id;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $loadingAddress;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $unloadingAddress;
    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $pricePerKm;
    /**
     * @var Driver
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Driver",inversedBy="cargoes")
     */
    private Driver $drivers;
    /**
     * @ORM\Column(type="integer" )
     */
    private int $status = 0;
    /**
     * @var User
     *@ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     */
    private User $author;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLoadingDate(): ?\DateTimeInterface
    {
        return $this->loadingDate;
    }

    public function setLoadingDate(\DateTimeInterface $loadingDate): self
    {
        $this->loadingDate = $loadingDate;

        return $this;
    }

    public function getUnloadingDate(): ?\DateTimeInterface
    {
        return $this->unloadingDate;
    }

    public function setUnloadingDate(?\DateTimeInterface $unloadingDate = null): self
    {
        $this->unloadingDate = $unloadingDate;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPricePerKm()
    {
        return $this->pricePerKm;
    }

    /**
     * @param mixed $pricePerKm
     */
    public function setPricePerKm($pricePerKm): void
    {
        $this->pricePerKm = $pricePerKm;
    }

    /**
     * @return mixed
     */
    public function getUnloadingAddress()
    {
        return $this->unloadingAddress;
    }

    /**
     * @param mixed $unloadingAddress
     */
    public function setUnloadingAddress($unloadingAddress): void
    {
        $this->unloadingAddress = $unloadingAddress;
    }

    /**
     * @return mixed
     */
    public function getTruckId()
    {
        return $this->truck_id;
    }

    /**
     * @param mixed $truck_id
     */
    public function setTruckId($truck_id): void
    {
        $this->truck_id = $truck_id;
    }

    /**
     * @return mixed
     */
    public function getLoadingAddress()
    {
        return $this->loadingAddress;
    }

    /**
     * @param mixed $loadingAddress
     */
    public function setLoadingAddress($loadingAddress): void
    {
        $this->loadingAddress = $loadingAddress;
    }



    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->loadingAddress." to ".$this->unloadingAddress;
    }

    /**
     * @param mixed $title
     */
    public function setTitle($title): void
    {
        $this->title = $title;
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }
    /**
     * @param mixed $status
     */
    public function setStatus($status): void
    {
        $this->status = $status;
    }
    /**
     * @return User
     */
    public function getAuthor(): User
    {
        return $this->author;
    }

    /**
     * @param User $author
     *
     */
    public function setAuthor(User $author )
    {
        $this->author = $author;
    }
    /**
     * @return Driver
     */
    public function getDrivers(): Driver
    {
        return $this->drivers;
    }

    /**
     * @param Driver $drivers
     */
    public function setDrivers(Driver $drivers): void
    {
        $this->drivers = $drivers;
    }


}`

**Comment by tattali** [comment]
It's probably because the end date is nullable
```diff
    /**
-     * @ORM\Column(type="datetime")
+     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?\DateTimeInterface $unloadingDate;
```

**Comment by Skatsarov123** [comment]
nothing happens
If i remove request param from function everything work fine
``` public function onCalendarSetData( CalendarEvent $calendar,Request $request):Response

**Comment by tattali** [comment]
Yes!
https://github.com/tattali/CalendarBundle/blob/master/src/Resources/doc/multi-calendar.md

**Comment by Skatsarov123** [comment]
Hi there.

Do you know how to pass select tag value in request

` eventSources: [
                {
                    url: "{{ path('fc_load_events') }}",


                    method: "POST",
                    extraParams: {
                        filters: JSON.stringify({}),
                        custom_param1: 'value'
                    },`

**Comment by tattali** [comment]
Hi,
you probably need to put the `custom_param1: 'value'` in the `filters` param

```
    extraParams: {
        filters: JSON.stringify({custom_param1: 'value'}),
    },
```

and then you can access to it in your subscriber by $filters['calendar-id']
```
public function onCalendarSetData(CalendarEvent $calendar)
{
        $filters = $calendar->getFilters();
        $filters['custom_param1']; // value
}
```
You dont need to call the `Request` component
As explain in https://github.com/tattali/CalendarBundle/blob/master/src/Resources/doc/multi-calendar.md

**Comment by Skatsarov123** [comment]
this is request dump from my controller and its work. statusId is for dropdown filter
```object(Symfony\Component\HttpFoundation\Request)#573 (24) { ["attributes"]=> object(Symfony\Component\HttpFoundation\ParameterBag)#576 (1) { ["parameters":protected]=> array(0) { } } ["request"]=> object(Symfony\Component\HttpFoundation\ParameterBag)#574 (1) { ["parameters":protected]=> array(1) **{ ["statusId"]=> string(1) "0" } }** ["query"]=> object(Symfony\Component\HttpFoundation\ParameterBag)#575 (1) { ["parameters":protected]=> array(0) { } } ["server"]=>

I want to put this value in callendar request

```object(Symfony\Component\HttpFoundation\Request)#585 (24) { ["attributes"]=> object(Symfony\Component\HttpFoundation\ParameterBag)#588 (1) { ["parameters":protected]=> array(0) { } } ["request"]=> object(Symfony\Component\HttpFoundation\ParameterBag)#586 (1) { ["parameters":protected]=> array(4) { ["filters"]=> string(2) "{}" ["start"]=> string(20) "2020-11-01T00:00:00Z" ["end"]=> string(20) "2020-12-13T00:00:00Z" ["timeZone"]=> string(3) "UTC" } } ["query"]=> object(Symfony\Component\HttpFoundation\ParameterBag)#587 (1) { ["parameters":protected]=> array(0) { } } ["server"]=>

**Comment by tattali** [comment]
where do you need to use the value ?

**Comment by Skatsarov123** [comment]
Your solution work.Only one problem left.Filter take only the first select tag option no matter what is selected

**Comment by tattali** [comment]
I don't think this is a trouble with this bundle. But share your code

**Comment by Skatsarov123** [comment]
```<form class="form-group" method="post">
        <table class="table">
            <tr>
                <td>
                    <label>
                        <select id="statusId" name="statusId">
                            <option value="1" >1</option>
                            <option value="0" >0</option>
                        </select>
                    </label>
                    <input id="submit" type="submit" value="show">
                </td>
            </tr>
        </table>
    </form>

``` public function onCalendarSetData(CalendarEvent $calendar)
    {
        $filters = $calendar->getFilters();
        $statusId= $filters['custom_param'];
        var_dump($statusId);
        $bookings = $this->getDoctrine()->getRepository(Booking::class)
                ->findBy(['author' => $this->getUser(), 'status' => $statusId]);
        foreach ($bookings as $booking) {
            $bookingEvent = new Event(
                $booking->getTitle(),
                $booking->getloadingDate(),
                $booking->getUnloadingDate(),

            );

**Comment by tattali** [comment]
Well can you also share the JS part and is it in the same file or in his own `.js` ?

**Comment by Skatsarov123** [comment]
```{% extends 'base.html.twig' %}

{% block body %}
    <form class="form-group" method="post">
        <table class="table">
            <tr>
                <td>
                    <label>
                        <select id="statusId" name="statusId">
                            <option value="1" >1</option>
                            <option value="0" >0</option>
                        </select>
                    </label>
                    <input id="submit" type="submit" value="show">
                </td>
            </tr>
        </table>
    </form>
    <div id="calendar-holder"></div>

{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('css/bootstrap-datetimepicker.min.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.1.0/main.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.1.0/main.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.1.0/main.min.css">

{% endblock %}

{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.1.0/main.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/interaction@4.1.0/main.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.1.0/main.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.1.0/main.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@fullcalendar/list@4.1.0/main.min.js"></script>

<div id="mycalendar"></div>

<script type="text/javascript">
    var value = document.getElementById("statusId").value;
    document.addEventListener('DOMContentLoaded', () => {
        var calendarEl = document.getElementById('calendar-holder');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            defaultView: 'dayGridMonth',
            editable: true,
            eventSources: [
                {
                    url: "{{ path('fc_load_events') }}",

                    method: "POST",
                    extraParams: {
                        filters: JSON.stringify({custom_param: document.getElementById("statusId").value}),

                    },
                    failure: () => {
                        // alert("There was an error while fetching FullCalendar!");
                    },
                },
            ],
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,list',
            },

            plugins: ['interaction', 'dayGrid', 'timeGrid', 'list'], // https://fullcalendar.io/docs/plugin-index
            timeZone: 'UTC',
            locale: "bg",

        });

        calendar.render();
    });
</script>

{% endblock %

**Comment by tattali** [comment]
Maybe you just have to add an event listener on change of your select 
```
document.getElementById("statusId").addEventListener("change", () => {
calendar.refetchEvents();
});
```

**Comment by Skatsarov123** [comment]
Nothing change .Still take first option value

**Comment by Skatsarov123** [comment]
i tried everything what i found ,but nothing.Cant pass selected value trough filter. addEventListener is not working.reply with first option,not with the selected one

**Comment by tattali** [comment]
I found out
```html
<select id="elselect">
    <option>ok</option>
    <option>ko</option>
</select>
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', () => {
        const selectToRegister = document.getElementById('elselect');
        var calendarEl = document.getElementById('calendar-holder');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            defaultView: 'dayGridMonth',
            editable: true,
            eventSources: [{
                url: "{{ path('fc_load_events') }}",
                method: "POST",
                extraParams: () => {
                    console.log(selectToRegister.value);
                    return {
                        filters: JSON.stringify({
                            custom_param: selectToRegister.value,
                        }),
                    };
                },
                failure: () => {
                    // alert("There was an error while fetching FullCalendar!");
                },
            }],
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,list',
            },
            plugins: ['interaction', 'dayGrid', 'timeGrid', 'list'], // https://fullcalendar.io/docs/plugin-index
            timeZone: 'UTC',
            locale: "bg",
        });

        calendar.render();

        selectToRegister.addEventListener('change', () => {
            calendar.refetchEvents();
        });
    });
</script>
```
or 
```html
<select id="elselect">
    <option>ok</option>
    <option>ko</option>
</select>
<script type="text/javascript">
    document.addEventListener('DOMContentLoaded', () => {
        const selectToRegister = document.getElementById('elselect');
        var calendarEl = document.getElementById('calendar-holder');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            defaultView: 'dayGridMonth',
            editable: true,
            eventSources: [{
                url: "{{ path('fc_load_events') }}",
                method: "POST",
                extraParams: () => ({
                    filters: JSON.stringify({
                        custom_param: selectToRegister.value,
                    }),
                }),
                failure: () => {
                    // alert("There was an error while fetching FullCalendar!");
                },
            }],
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'dayGridMonth,list',
            },
            plugins: ['interaction', 'dayGrid', 'timeGrid', 'list'], // https://fullcalendar.io/docs/plugin-index
            timeZone: 'UTC',
            locale: "bg",
        });

        calendar.render();

        selectToRegister.addEventListener('change', () => {
            calendar.refetchEvents();
        });
    });
</script>
```

**Comment by Skatsarov123** [comment]
Thanks man! Works like a charm

**Comment by tattali** [comment]
Great! I close your issue then!
Feel free to reopen it if the error come up
