### ISSUE TITLE
Why i can't use DateTime on my project after install CalendarBundle

### ISSUE THREAD

**Issue by skPink** [tattali/CalendarBundle#36]
Hi,

After i downlaod CalendarBundle i can't use new DateTime() or pass datetime var on respository i have this error : 

The class 'DateTime' was not found in the chain configured namespaces App\Entity, CalendarBundle\Entity

on symfony 5.1

@tattali Thx

**Comment by tattali** [comment]
use `new \DateTime()` or add a `use DateTime;` under namespaces

**Comment by skPink** [comment]
@tattali Not working i add use DateTime on my repository but i have error

**Comment by tattali** [comment]
did you do a `composer update` ?

It's an error from doctrine orm, rerun `composer update` they maybe release the or reverse to your original doctrine version

to update only one package run `composer update tattali/calendar-bundle other-package/to-update`

https://stackoverflow.com/questions/65148281/the-class-datetime-was-not-found-in-the-chain-configured-namespaces-app-entity
