### ISSUE TITLE
Unable to generate a URL for the named route "fc_load_events" as such route does not exist.

### ISSUE THREAD

**Issue by aa-aahmed** [tattali/CalendarBundle#37]
Symfony 4.4.20

Boys, I have the same issue. Bundle is enabled, Services are registered.

`An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "fc_load_events" as such route does not exist.").`

Composer:

```
"scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
```

Also I notice when I install the bundle, recipe does not register bundle automatically, I had to manually register this bundle.

Please let me know if you want me to open a new issue or you ok with this. I thought if all comments are at one place then it would be easier for others to find.

```
bin/console debug:router fc-load-events
The route "fc-load-events" does not exist.
```

**Comment by tattali** [comment]
Hi, I have followed the steps for a fresh install of symfony 4.4.21 and it is working fine. Are you sure you have the `tattali / calendar-bundle` bundle installed ?

**Comment by aa-aahmed** [comment]
sorry i had a issue with my dev machine that was causing the issue. Everything seems to be working fine.
