### ISSUE TITLE
Display icon in title

### ISSUE THREAD

**Issue by davidromani** [tattali/CalendarBundle#39]
Hi,

Can I render a raw HTML tag inside an event title? I need to show a "classic" `<i class="fa fa-comment"/>` icon before the event title.

Thanks.

**Comment by tattali** [comment]
Hi, you can add a `customHtml` option, and then trigger it in event content.
https://codepen.io/arshaw/pen/ExPXjpY?editable=true&editors=001

https://fullcalendar.io/docs/event-render-hooks
https://fullcalendar.io/docs/content-injection

**Comment by davidromani** [comment]
@tattali thanks for your answer, I'll try it but I was thinking about how to do it into a subscriber (without JS).

https://github.com/tattali/CalendarBundle/blob/master/src/Resources/doc/doctrine-crud.md#full-subscriber

**Comment by Luvelnet** [comment]
Hello,

I take this opportunity to ask, if you can change the background of a full day, for example to indicate the holidays. Without JS, directly in subscriber.

Thanks!

**Comment by davidromani** [comment]
> Hello,
> 
> I take this opportunity to ask, if you can change the background of a full day, for example to indicate the holidays. Without JS, directly in subscriber.
> 
> Thanks!

@Luvelnet maybe this code helps you...

```
class CalendarSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            CalendarEvents::SET_DATA => 'onCalendarSetData',
        ];
    }

    public function onCalendarSetData(CalendarEvent $calendar): void
    {
        $start = $calendar->getStart();
        $end = $calendar->getEnd();
        // tasks
        $tasks = $this->repositoriesManager->getTaskRepository()->getByDueDateInterval($start, $end)->getQuery()->getResult();
        /** @var Task $task */
        foreach ($tasks as $task) {
           $fcEvent = new Event($task->getTitle(), $task->getStart());
           $fcEvent->setEnd($task->getEnd());
           $fcEvent->setAllDay($task->getAllDay());
           $fcEvent->setOptions([
                'background' => $task->getBackgroundColor(),
                'text' => $task->getBackgroundColor(),
                'customHtml' => $task->getBackgroundColor(),
                'color' => $task->getBackgroundColor(),
                'url' => $this->router->generate($task->getUrl(), ['id' => $task->getId()], UrlGeneratorInterface::ABSOLUTE_PATH),
            ]);
            $calendar->addEvent($fcEvent);
        }
    }
}
```

Task class is my own data model, Event is from CalendarBundle.
