### ISSUE TITLE
Referencing controllers with CalendarBundle:Calendar:load is deprecated

### ISSUE THREAD

**Issue by ehymel** [tattali/CalendarBundle#4]
Using symfony 4.2, I am seeing this warning in the profiler:

> Referencing controllers with CalendarBundle:Calendar:load is deprecated since Symfony 4.1, use "CalendarBundle\Controller\CalendarController::loadAction" instead.

This appears to be coming from your file `src/Resources/config/routing.yaml`. A minor thing to be sure, but worth mentioning.

**Comment by tattali** [comment]
Thanks for the feedback
