### ISSUE TITLE
Long event not showing up in the middle

### ISSUE THREAD

**Issue by haivala** [tattali/CalendarBundle#45]
I have calendar that has allDay false for events in symfony installation and I'm using only week and day view
My event loader uses this 
```
    public function findItemBookings($start, $end, $filters)
    {
        return $this->createQueryBuilder('booking')
            ->where('booking.beginAt BETWEEN :start and :end OR booking.endAt BETWEEN :start and :end')
            ->andWhere('booking.item = :itemId')
            ->setParameter('start', $start->format('Y-m-d H:i:s'))
            ->setParameter('end', $end->format('Y-m-d H:i:s'))
            ->setParameter('itemId', $filters['item'])
            ->getQuery()
            ->getResult()
        ;
    }
```
And I tested this:
```
document.addEventListener('DOMContentLoaded', function() {
  var calendarEl = document.getElementById('calendar');

  var calendar = new FullCalendar.Calendar(calendarEl, {
    initialView: 'timeGridWeek',
    initialDate: '2021-07-07',
    allDaySlot: false,        
    eventOverlap: false,
    selectOverlap: false,
    editable: false,
    headerToolbar: {
      left: 'prev,next today',
      center: 'title',
      right: 'dayGridMonth,timeGridWeek,timeGridDay'
    },
    events: [
      {
        allDay: false,
        title: 'Long Event',
        start: '2021-07-07T10:00:00',
        end: '2021-07-20T12:00:00'
      }
    ]
  });

  calendar.render();
});
```
and that it is working.

# the problem
In week view I can see when the long event starts then I go to the next week the calendar **is empty** and then I go to the next week I can see the event ending. In day view it is the same problem. event shows up on the start and end dates.
I checked the js request and it is empty when the calendar is empty.
Is this problem with this bundle or have I done something wrong?

**Comment by haivala** [comment]
I guess this
```
->where('booking.beginAt BETWEEN :start and :end OR booking.endAt BETWEEN :start and :end')
```
has to be more complicated

**Comment by haivala** [comment]
```
->where('booking.beginAt < :start AND booking.endAt > :end OR booking.beginAt BETWEEN :start and :end OR booking.endAt BETWEEN :start and :end')
```
is the answer, but does this work properly any all cases?

**Comment by tsiatka** [comment]
Thanks for the quick fix
I was having the same issue

**Comment by tattali** [comment]
Hi, your query fetch more or less all events
try
```->where(':start BETWEEN booking.beginAt and booking.endAt OR :end BETWEEN booking.beginAt and booking.endAt')```

**Comment by haivala** [comment]
I haven't had any problems with it. @tsiatka ?

**Comment by tsiatka** [comment]
both suggested queries seems to work in my case
