### ISSUE TITLE
Performance issue in CalendatEvent class

### ISSUE THREAD

**Issue by fdiedler** [tattali/CalendarBundle#46]
Hi,

After profiling my code, I found a performance issue in this function : 

```
    public function addEvent(Event $event): self
    {
        if (!\in_array($event, $this->events, true)) {
            $this->events[] = $event;
        }
        return $this;
    }
```

Indeed, the performance of _in_array()_ php function is horrible. Can you provide another function using _isset_() or even with no verification of duplicates ?

You can see in the Symfony Profiler, 1500ms to load 27 000 events without the check in addEvent() function VS 3100ms...

![without_check](https://user-images.githubusercontent.com/42271872/148070485-a7de43ec-fcc8-4d98-842e-5dac2e797de0.png)
![with_inarray](https://user-images.githubusercontent.com/42271872/148070492-968321b9-c958-4447-86e3-2d42f9a73337.png)
,
Thanks,

**Comment by Chris53897** [comment]
@fdiedler Can you please check the new Version 1.2.4?
I guess this Issue can be closed.
