### ISSUE TITLE
More than one Event Entity

### ISSUE THREAD

**Issue by Dr-Ash** [tattali/CalendarBundle#5]
Hello,

Is it possible to make the calendar deal with more than one Entity as events source?

**Comment by tattali** [comment]
Hi, yes of course! One way would be to query your other entity and add an other foreach to your listener.

```php
        $bookings = /* First query */;

        foreach ($bookings as $booking) {
            $bookingEvent = new Event(/* Parameters */);

            $calendar->addEvent($bookingEvent);
        }

        $collection = /* Second query */;

        foreach ($collection as $otherEntity) {
            $otherEntityEvent = new Event(/* Parameters */);

            $calendar->addEvent($otherEntityEvent);
        }
```

Hope this will help you

**Comment by dubitoph** [comment]
Hello,

I use Symfony 4..2.1.

I meet a problem when I try to get the filters.  I implement the filter variable in the javascript like this : 
  `            eventSources: [
                            {

                                url: "/fc-load-events",
                                type: "POST",
                                data: {

                                        filters: {"vehicle": 1},

                                    },
                                error: () => {

                                                alert("There was an error while fetching FullCalendar!");

                                             },

                            },
                          ],`
In my listener, I get the filters with `$filters = $calendar->getFilters();`. When I try to get the specific filter with `$vehicle = $filters['vehicle'];`, I have this error : 

"Notice: Undefined index: vehicle"
