### ISSUE TITLE
Events not showing

### ISSUE THREAD

**Issue by DamienBuchet** [tattali/CalendarBundle#54]
Hi, 
I tried to use this in my project (Symfony 6), and the Events aren't showing, there is just the calendar. I used the code that was given here, and made different attempts with differents datetimes, without any result. I got a bunch of errors, and I don't know from where they're coming, so if someone has an idea, thanks by advance.
![image](https://user-images.githubusercontent.com/60095199/173604545-87d2804f-3941-4dea-8746-933c2eae5421.png)

**Comment by tattali** [comment]
Which documentation did you follow?

**Comment by DamienBuchet** [comment]
I used the one on the front page : [https://github.com/tattali/CalendarBundle](url)
But I think I guessed the problem, I made a redirect from the public folder to access it from the root
