### ISSUE TITLE
Support Symfony 7

### ISSUE THREAD

**Issue by tacman** [tattali/CalendarBundle#62]
It'll be out in less than 2 months.

The AssetMapper component is a gamechanger.  I'm working on a demo now (still stuck at getting fullcalendar to work without the bundle, see https://github.com/tacman/micro-calendar for my repo and https://github.com/fullcalendar/fullcalendar/issues/7472 for the specific issue.

I'm thinking support for Symfony 7 could be version 2.0, only support Symfony 6.4 and 7, PHP 8.1+.

**Comment by tattali** [comment]
A support for Symfony 7 would be very nice!

I answer on your issue of the fullcalendar repo

See you!

**Comment by tattali** [comment]
I just saw that Symfony 7 will be available for php 8.2 and above

https://github.com/symfony/symfony/blob/7.0/composer.json

**Comment by tacman** [comment]
What do you think about a 2.0 of this bundle, Symfony 6.4||^7 only?

The primary reason is AssetMapper, but also the Twig Components.  I can't
wait to implement and see <twig:calendar :ics="icsUrl" />!

**Comment by tattali** [comment]
Can't wait to see seems a wonderful idea using types and deprecate old code.

Thanks for your help

**Comment by Chris53897** [comment]
I have created a [PR for Symfony 7](https://github.com/tattali/CalendarBundle/pull/64) before i did read this issue.
This will give some time to work on an version like @tacman proposed.

**Comment by tacman** [comment]
Thanks for implementing this!
