### ISSUE TITLE
New release with latest changes

### ISSUE THREAD

**Issue by tacman** [tattali/CalendarBundle#79]
I'm getting this error when installing in a Symfony 7 application

```
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In DefinitionErrorExceptionPass.php line 48:
!!                                                                                 
!!    Cannot autowire service "CalendarBundle\Controller\CalendarController": arg  
!!    ument "$container" of method "Symfony\Bundle\FrameworkBundle\Controller\Abs  
!!    tractController::setContainer()" references interface "Psr\Container\Contai  
!!    nerInterface" but no such service exists. Did you mean to target "parameter  
!!    _bag" instead?                                                               
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd
```

I'm pretty sure it's because it's not getting the dev (master) branch.  Can you publish a new release, so packagist automatically gets the right one please?

Thx.

**Comment by BretonLud** [comment]
Hi,

Yeah, I think I have the same problem:

![image](https://github.com/user-attachments/assets/bd5f0568-d6cc-42dc-b893-4a3d96c1ac17)

`CalendarEvent.php` was renamed to `SetDateEvent.php` in a commit on either 2024-04-20 or 2024-05-02.

My project is on symfony 7.1

**Comment by Chris53897** [comment]
Related to https://github.com/tattali/CalendarBundle/pull/80/files

**Comment by tattali** [comment]
Closes by https://github.com/tattali/CalendarBundle/releases/tag/v7.0.0

**Comment by tacman** [comment]
Please reopen, this doesn't work:

```bash
symfony new --webapp calendar-demo && cd calendar-demo && composer require tattali/calendar-bundle
```

**Comment by Chris53897** [comment]
@tacman @tattali 

I fixed this as a workaround in my project by adding this line to `config/service.yaml`

`Psr\Container\ContainerInterface: '@service_container'`

I use 7.0 of this bundle. So many users will have this issue.

**Comment by tacman** [comment]
I refactored the bundle in my branch, but am not sure it's ready for a PR yet.  

https://github.com/tacman/CalendarBundle/tree/tac

It uses the modern directory structure, and all the DI has been moved into the bundle class itself.  The source directory looks ~~sparse~~ clean.

~/g/tacman/CalendarBundle$ tree src/
src/
├── CalendarBundle.php
├── Controller
│   └── CalendarController.php
├── Entity
│   └── Event.php
└── Event
    └── SetDataEvent.php


If so inclined, please test it

**Comment by Chris53897** [comment]
Thanks for wirking on this. I did a quick test.
I am not sure if it works correct. The calendar does give back results, but `symfony console c:c` is getting me
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 655360 bytes) in xxx/vendor/twig/twig/src/NodeVisitor/SafeAnalysisNodeVisitor.php on line 77

I did delete the cache folder and calender did work.
But as there are many updates with PHP 8.4 and Symfony 7.2 i need to have a closer look.

"tattali/calendar-bundle": "dev-tac",
...
,
    "repositories": {
        "calendar": {
            "type": "vcs",
            "url": "git@github.com:tacman/CalendarBundle.git"
        }
    }


Changed config/routes/calendar.yml to

calendar:
    #resource: "@CalendarBundle/Resources/config/routing.yaml"
    resource: "@CalendarBundle/config/routing.yaml"

**Comment by tattali** [comment]
Normaly their is no twig dependencies

**Comment by tacman** [comment]
No twig in the bundle, just in the demo.
 
    composer show | grep twig

I need to update the demo app.

**Comment by Chris53897** [comment]
I did the test it in a project that is useing EassyAdmin and run into https://github.com/EasyCorp/EasyAdminBundle/issues/6605#event-15492475752

I am in favour of seperate PRs to fix the root cause of the error.
And a seperate PR to move to the new bundle structure.

**Comment by tacman** [comment]
Here's a demo app using the new structure.

```bash
git clone git@github.com:survos-sites/calendar-demo.git 
cd calendar-demo
composer install
symfony server:start -d
symfony open:local
```
