### ISSUE TITLE
What about the other events?

### ISSUE THREAD

**Issue by villalvilla** [tattali/CalendarBundle#8]
Hi,

Nice work, but lot more work has to be done, I presume.
With the actual work, it is impossible to let symfony know about creation, edition and delete events. They have to be generated "your own way" in ajax and creating actions in the controllers to make it work. Which is the real purpose of your symfony bundle if it doen't do "the real work"? I mean, if you can only load the contents from the database to the calendar with your bundle, why not doing it "the dirty way" for everything and also bypassing fc-load-events and directly calling controller's CRUD actions from fullcalendar?

I think that the rest of the events should be created in your bundle and attended as services to make everything work as expected. If not, using your bundle won't help so much. Let me know if I can help on this.

**Comment by tattali** [comment]
Hi, have you read the documentation about the CRUD : https://github.com/tattali/CalendarBundle/blob/master/src/Resources/doc/doctrine-crud.md

**Comment by villalvilla** [comment]
Hi tattali,
Of course I did, but if I connect booking_show to every event's url, the ajax call will only fire on edit/update, not when I create a new event in the calendar. Maybe I am missing something/missinterpreting your documentation.

Thanks for the feedback

**Comment by tattali** [comment]
The ajax call is only configured to GET the events from the database.

Have you added the link to the create form, as in part 5 of the documentation?
https://github.com/tattali/CalendarBundle/blob/master/src/Resources/doc/doctrine-crud.md#5-display-your-calendar

If you prefer, you can put the calendar in the same template as the create form.

**Comment by ehymel** [comment]
I for one appreciate the bundle. The creation of the service that loads the calendar data is nice, and tweaking the service to my own needs was nicer than creating all scratch. The beauty of github is that you can submit PR's to extend or just fork the project and do your own thing. No need to diminish the hard work that someone has put into things!

**Comment by villalvilla** [comment]
> 
> 
> I for one appreciate the bundle. The creation of the service that loads the calendar data is nice, and tweaking the service to my own needs was nicer than creating all scratch. The beauty of github is that you can submit PR's to extend or just fork the project and do your own thing. No need to diminish the hard work that someone has put into things!

Of course I am really apreciating tattai's work and not diminishing his work at all! I am just trying to give some ideas on how to improve his work to make it better for everybody. With his architechture and a little bit more effort, it could became a great read/write plugin, and not a read-only one. Wrapping events in symfony is a great idea, and with a couple more events it could be awesome. The only problem I see is that js library should be modified acording this library... Maybe adding a new plugin that could fire events and redirect them to "standarised" symfony's consumers?

Again, thanks for your great effort and let me know if I could help implementing CRUD event's handler.

**Comment by tattali** [comment]
Of course, if you want to submit a PR, you are welcome
